class LocalizationService {
  static const Map<String, Map<String, String>> _localizedValues = {
    'id': {
      // Common
      'app_title': 'Perpustakaan Stephen King',
      'login': 'Masuk',
      'logout': 'Keluar',
      'register': 'Daftar',
      'email': 'Email',
      'password': 'Kata Sandi',
      'name': 'Nama',
      'confirm_password': 'Konfirmasi Kata Sandi',
      'save': 'Simpan',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'edit': 'Edit',
      'add': 'Tambah',
      'search': 'Cari',
      'loading': 'Memuat...',
      'error': 'Terjadi kesalahan',
      'success': 'Berhasil',
      'settings': 'Pengaturan',
      'language': 'Bahasa',
      'indonesian': 'Bahasa Indonesia',
      'english': 'English',
      
      // Home Screen
      'welcome': 'Selamat Datang',
      'user_info': 'Informasi Pengguna',
      'quick_actions': 'Aksi Cepat',
      'book_collection': 'Koleksi Buku',
      'stephen_king_books': 'Buku Stephen King',
      'manage_books': 'Kelola Buku',
      'add_edit_books': 'Tambah & edit buku',
      'manage_members': 'Kelola Member',
      'member_management': 'Manajemen anggota',
      'borrowing': 'Peminjaman',
      'book_borrowing': 'Peminjaman buku',
      'reports': 'Laporan',
      'library_reports': 'Laporan perpustakaan',
      'role': 'Peran',
      'status': 'Status',
      'join_date': 'Tanggal Bergabung',
      'active': 'Aktif',
      'admin': 'Admin',
      'user': 'Pengguna',
      
      // Books
      'books': 'Buku',
      'book_title': 'Judul Buku',
      'author': 'Penulis',
      'publisher': 'Penerbit',
      'year': 'Tahun',
      'pages': 'Halaman',
      'isbn': 'ISBN',
      'notes': 'Catatan',
      'villains': 'Penjahat',
      'book_details': 'Detail Buku',
      'add_book': 'Tambah Buku',
      'edit_book': 'Edit Buku',
      'book_info': 'Informasi Buku',
      'publication_info': 'Informasi Publikasi',
      'additional_info': 'Informasi Tambahan',
      
      // Members
      'members': 'Anggota',
      'member_name': 'Nama Anggota',
      'phone': 'Telepon',
      'address': 'Alamat',
      'member_id': 'ID Anggota',
      'registration_date': 'Tanggal Daftar',
      'add_member': 'Tambah Anggota',
      'edit_member': 'Edit Anggota',
      'member_details': 'Detail Anggota',
      
      // Loans
      'loans': 'Peminjaman',
      'all': 'Semua',
      'overdue': 'Terlambat',
      'all_loans': 'Semua Peminjaman',
      'active_loans': 'Peminjaman Aktif',
      'overdue_loans': 'Peminjaman Terlambat',
      'loan_date': 'Tanggal Pinjam',
      'due_date': 'Tanggal Kembali',
      'return_date': 'Tanggal Dikembalikan',
      'loan_status': 'Status Peminjaman',
      'borrowed': 'Dipinjam',
      'returned': 'Dikembalikan',
      'add_loan': 'Tambah Peminjaman',
      'return_book': 'Kembalikan Buku',
      'select_member': 'Pilih Anggota',
      'select_book': 'Pilih Buku',
      'days_overdue': 'hari terlambat',
      'create_new_loan': 'Buat Peminjaman Baru',
      'create_loan': 'Buat Peminjaman',
      'book_source': 'Sumber Buku',
      'local_books': 'Buku Lokal',
      'online_books': 'Buku Online',
      'search_books': 'Cari Buku',
      'no_books_found': 'Tidak ada buku ditemukan',
      'stock': 'Stok',
      'book_not_available': 'Buku tidak tersedia atau anggota sudah meminjam buku ini',
      'loan_created_success': 'Peminjaman berhasil dibuat',
      'error_creating_loan': 'Gagal membuat peminjaman',
      'search_error': 'Gagal mencari buku',
      'api_load_error': 'Gagal memuat buku dari API',
      
      // Messages
      'login_success': 'Berhasil masuk',
      'login_failed': 'Email atau kata sandi salah',
      'register_success': 'Berhasil mendaftar',
      'register_failed': 'Gagal mendaftar',
      'password_mismatch': 'Kata sandi tidak cocok',
      'fill_all_fields': 'Harap isi semua field',
      'book_added': 'Buku berhasil ditambahkan',
      'book_updated': 'Buku berhasil diperbarui',
      'book_deleted': 'Buku berhasil dihapus',
      'member_added': 'Anggota berhasil ditambahkan',
      'member_updated': 'Anggota berhasil diperbarui',
      'member_deleted': 'Anggota berhasil dihapus',
      'loan_added': 'Peminjaman berhasil ditambahkan',
      'book_returned': 'Buku berhasil dikembalikan',
      'feature_under_development': 'Fitur sedang dalam pengembangan',
      'language_changed': 'Bahasa berhasil diubah',
    },
    'en': {
      // Common
      'app_title': 'Stephen King Library',
      'login': 'Login',
      'logout': 'Logout',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'confirm_password': 'Confirm Password',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'loading': 'Loading...',
      'error': 'An error occurred',
      'success': 'Success',
      'settings': 'Settings',
      'language': 'Language',
      'indonesian': 'Bahasa Indonesia',
      'english': 'English',
      
      // Home Screen
      'welcome': 'Welcome',
      'user_info': 'User Information',
      'quick_actions': 'Quick Actions',
      'book_collection': 'Book Collection',
      'stephen_king_books': 'Stephen King Books',
      'manage_books': 'Manage Books',
      'add_edit_books': 'Add & edit books',
      'manage_members': 'Manage Members',
      'member_management': 'Member management',
      'borrowing': 'Borrowing',
      'book_borrowing': 'Book borrowing',
      'reports': 'Reports',
      'library_reports': 'Library reports',
      'role': 'Role',
      'status': 'Status',
      'join_date': 'Join Date',
      'active': 'Active',
      'admin': 'Admin',
      'user': 'User',
      
      // Books
      'books': 'Books',
      'book_title': 'Book Title',
      'author': 'Author',
      'publisher': 'Publisher',
      'year': 'Year',
      'pages': 'Pages',
      'isbn': 'ISBN',
      'notes': 'Notes',
      'villains': 'Villains',
      'book_details': 'Book Details',
      'add_book': 'Add Book',
      'edit_book': 'Edit Book',
      'book_info': 'Book Information',
      'publication_info': 'Publication Information',
      'additional_info': 'Additional Information',
      
      // Members
      'members': 'Members',
      'member_name': 'Member Name',
      'phone': 'Phone',
      'address': 'Address',
      'member_id': 'Member ID',
      'registration_date': 'Registration Date',
      'add_member': 'Add Member',
      'edit_member': 'Edit Member',
      'member_details': 'Member Details',
      
      // Loans
      'loans': 'Loans',
      'all': 'All',
      'overdue': 'Overdue',
      'all_loans': 'All Loans',
      'active_loans': 'Active Loans',
      'overdue_loans': 'Overdue Loans',
      'loan_date': 'Loan Date',
      'due_date': 'Due Date',
      'return_date': 'Return Date',
      'loan_status': 'Loan Status',
      'borrowed': 'Borrowed',
      'returned': 'Returned',
      'add_loan': 'Add Loan',
      'return_book': 'Return Book',
      'select_member': 'Select Member',
      'select_book': 'Select Book',
      'days_overdue': 'days overdue',
      'create_new_loan': 'Create New Loan',
      'create_loan': 'Create Loan',
      'book_source': 'Book Source',
      'local_books': 'Local Books',
      'online_books': 'Online Books',
      'search_books': 'Search Books',
      'no_books_found': 'No books found',
      'stock': 'Stock',
      'book_not_available': 'Book is not available or member already has this book',
      'loan_created_success': 'Loan created successfully',
      'error_creating_loan': 'Error creating loan',
      'search_error': 'Error searching books',
      'api_load_error': 'Error loading books from API',
      
      // Messages
      'login_success': 'Login successful',
      'login_failed': 'Invalid email or password',
      'register_success': 'Registration successful',
      'register_failed': 'Registration failed',
      'password_mismatch': 'Passwords do not match',
      'fill_all_fields': 'Please fill all fields',
      'book_added': 'Book added successfully',
      'book_updated': 'Book updated successfully',
      'book_deleted': 'Book deleted successfully',
      'member_added': 'Member added successfully',
      'member_updated': 'Member updated successfully',
      'member_deleted': 'Member deleted successfully',
      'loan_added': 'Loan added successfully',
      'book_returned': 'Book returned successfully',
      'feature_under_development': 'Feature under development',
      'language_changed': 'Language changed successfully',
    },
  };
  
  static String getText(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
  
  static Map<String, String> getTexts(String languageCode) {
    return _localizedValues[languageCode] ?? _localizedValues['id']!;
  }
}