// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtUjludALKtw3XjGDEyWuss9Zyp0nlP1o',
    appId: '1:982415778411:web:c4f727af54ca6867b7c72e',
    messagingSenderId: '982415778411',
    projectId: 'septinna-perpustakaan',
    authDomain: 'septinna-perpustakaan.firebaseapp.com',
    storageBucket: 'septinna-perpustakaan.firebasestorage.app',
    measurementId: 'G-KMFVLHCMF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanVhX1njqRcdsSP-jv4LiO2wPdUyhaJY',
    appId: '1:982415778411:android:5f00b9c555d688bfb7c72e',
    messagingSenderId: '982415778411',
    projectId: 'septinna-perpustakaan',
    storageBucket: 'septinna-perpustakaan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUsDb82L1KEAg2e9xWv_3Ag2jtsm_sBI',
    appId: '1:982415778411:ios:7354c94e0fa29165b7c72e',
    messagingSenderId: '982415778411',
    projectId: 'septinna-perpustakaan',
    storageBucket: 'septinna-perpustakaan.firebasestorage.app',
    iosBundleId: 'com.example.perpustakaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUsDb82L1KEAg2e9xWv_3Ag2jtsm_sBI',
    appId: '1:982415778411:ios:7354c94e0fa29165b7c72e',
    messagingSenderId: '982415778411',
    projectId: 'septinna-perpustakaan',
    storageBucket: 'septinna-perpustakaan.firebasestorage.app',
    iosBundleId: 'com.example.perpustakaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtUjludALKtw3XjGDEyWuss9Zyp0nlP1o',
    appId: '1:982415778411:web:6a8809810fbcaa41b7c72e',
    messagingSenderId: '982415778411',
    projectId: 'septinna-perpustakaan',
    authDomain: 'septinna-perpustakaan.firebaseapp.com',
    storageBucket: 'septinna-perpustakaan.firebasestorage.app',
    measurementId: 'G-Z3NYVW6GVJ',
  );
}
